### PR TITLE
Add Shimmer genesis snapshot

### LINKED ISSUE #1683: Verify genesis snapshot with community members

### PR DESCRIPTION
**Pull request by muXxer**
It's time to verify the Shimmer genesis snapshot!

To do this, we need the help of our community.

## Please follow the next steps:

- Copy the following bash script into a file called `create_shimmer_genesis.sh`

```bash
#!/bin/bash

if [[ "$OSTYPE" != "darwin"* && "$EUID" -ne 0 ]]; then
  echo "Please run as root or with sudo"
  exit
fi

# create data dir
if [ ! -d data ]; then
    echo "data directory not found. Creating..."
    mkdir data    
fi

# remove old results
if [ -f data/genesis_snapshot.bin ]; then
    rm data/genesis_snapshot.bin
fi

if [ ! -f data/protocol_parameters.json ]; then
    echo "Shimmer protocol parameters not found. Downloading..."
    curl -L https://github.com/iotaledger/global-snapshots/raw/shimmer-genesis/shimmer/protocol_parameters.json -o data/protocol_parameters.json
fi

if [ ! -f data/shimmer.json ]; then
    echo "Shimmer staking results not found. Downloading..."
    curl -L https://github.com/iotaledger/participation-events/raw/master/results/staking/shimmer.json -o data/shimmer.json
fi

if [ ! -f data/genesis_snapshot_orig.bin ]; then
    echo "Shimmer genesis snapshot (original) not found. Downloading..."
    curl -L https://github.com/iotaledger/global-snapshots/raw/shimmer-genesis/shimmer/genesis_snapshot.bin -o data/genesis_snapshot_orig.bin
fi

# set correct permissions
if [[ "$OSTYPE" != "darwin"* ]]; then
    chown -R 65532:65532 data
fi

# create genesis snapshot from Shimmer staking results + Treasury DAO + Tangle Association addresses
docker run --mount type=bind,source="$(pwd)"/data,target=/app/data \
    iotaledger/hornet:2.0.0-beta.8 \
    tool snap-gen --protocolParametersPath data/protocol_parameters.json \
    --genesisAddressesPath=data/shimmer.json \
    --genesisAddresses=smr1qrmakyqt5ezm5k9c0sk39gwfavpktxkjmx0jvh9ejxjq6pr6d39egv2mvuc:181362050906137,smr1qpjva0y6qwjmv42dspw2se2776l5qr0r5p2s5m7nrg73qhvm6a6y7uvqxn6:181362050906136 \
    --outputPath data/genesis_snapshot.bin

# print genesis snapshot hash
docker run --mount type=bind,source="$(pwd)"/data,target=/app/data \
    iotaledger/hornet:2.0.0-beta.8 \
    tool snap-hash --fullSnapshotPath data/genesis_snapshot.bin

# print sha256 hashes
echo "calculating SHA256 hashes..."
shasum -a 256 data/genesis_snapshot*.bin
```

## What does this script do?
- it downloads the initial protocol parameters for the Shimmer network which are attached to this PR.
- it downloads the community verified result of the Shimmer staking from https://github.com/iotaledger/participation-events/pull/2
- it adds the two additional addresses for the "initial [Shimmer Ecosystem Funding Proposal](https://govern.iota.org/t/discussion-proposal-to-increase-the-shimmer-supply-for-a-community-treasury/1291) and its [follow-up proposal](https://govern.iota.org/t/discussion-follow-up-proposal-to-the-establishment-of-a-shimmer-ecosystem-fund/1315)" which was decided and verified by the community here https://github.com/iotaledger/participation-events/pull/10
- it creates a genesis snapshot with all the downloaded information
- it downloads the "original" genesis snapshot which is attached to this PR
- it calculates the SHA256 of the generated and the downloaded genesis snapshot files

## What do I need to check?
- please verify that the content of the downloaded `protocol_parameters.json` is correct according to https://github.com/iotaledger/tips/blob/main/tips/TIP-0032/tip-0032.md#global-parameters
- please verify that the two additional addresses for the "initial [Shimmer Ecosystem Funding Proposal](https://govern.iota.org/t/discussion-proposal-to-increase-the-shimmer-supply-for-a-community-treasury/1291) and its [follow-up proposal](https://govern.iota.org/t/discussion-follow-up-proposal-to-the-establishment-of-a-shimmer-ecosystem-fund/1315)" in the above script are correct according to https://github.com/iotaledger/tips/blob/main/tips/TIP-0032/tip-0032.md#genesis-supply
- execute the script with `sudo ./create_shimmer_genesis.sh` and check that the shown SHA256 of the generated and the downloaded genesis snapshot files match

Please approve this PR in case you are sure that everything is correct.

### CODE REVIEW

**Review by lzpap — APPROVED** [review]
Verified! :rocket: 

```
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 529ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Review by shufps — APPROVED** [review]
LGTM:

loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 509ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

Also confirmed the two extra SMR genesis addresses and amounts are correct :heavy_check_mark:

**Comment by Dr-Electron** [comment]
- [x] Verified protocol parameters
- [x] Verified two additional addresses
- [x] Executed script and made sure hashes match

```
loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 628ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Review by Dr-Electron — APPROVED** [review]

**Review by no8ody — APPROVED** [review]
```
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 01:00:00 +0100 CET
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot_orig.bin
```

**Review by MaKla89 — APPROVED** [review]
Looking good over here!

Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 962ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

**Comment by klinkigt** [comment]
here you go:

loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 470ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin


only snapshot time seems quite a bit off ;)

**Comment by DerAnhalter** [comment]
```
loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 01:00:00 +0100 CET
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 579ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  ./genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  ./genesis_snapshot_orig.bin
```

**Review by ockerocker — APPROVED** [review]
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 532ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot_orig.bin

Press any key to continue

**Comment by SeeUnsharp** [comment]
loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 371ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

**Comment by RockLloque** [comment]
```zsh
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 555ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Review by DerAnhalter — APPROVED** [review]

**Review by mag-node — APPROVED** [review]
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 01:00:00 +0100 CET
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 688ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot_orig.bin

**Comment by pasrom** [comment]
```
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 358ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Review by p00dl — APPROVED** [review]
Verified!
image

**Review by pasrom — APPROVED** [review]

**Review by fhb191309 — APPROVED** [review]
Verified!

shimmer-genesis-creation

**Review by 0xKtota — APPROVED** [review]
image

**Comment by OMSKremer** [comment]
Verified!
```
Snapshot creation successful!
calculating ledger state hash ...
>
- Healthy: YES
- Tainted: NO
- Snapshot time: 1970-01-01 00:00:00 +0000 UTC
- Network ID: 14364762045254553490
- Treasury: milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
- Ledger index: 0
- Snapshot index: 0
- Pruning index: 0
- UTXOs count: 100665
- SEPs count: 1
- Ledger token supply: 1813620509061365
- Ledger state hash (w/o solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
- Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
- Protocol parameters hash (current+pending): b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 301ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd data/genesis_snapshot_orig.bin
```

**Review by OMSKremer — APPROVED** [review]
Verified
```
Snapshot creation successful!
calculating ledger state hash ...
>
- Healthy: YES
- Tainted: NO
- Snapshot time: 1970-01-01 00:00:00 +0000 UTC
- Network ID: 14364762045254553490
- Treasury: milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
- Ledger index: 0
- Snapshot index: 0
- Pruning index: 0
- UTXOs count: 100665
- SEPs count: 1
- Ledger token supply: 1813620509061365
- Ledger state hash (w/o solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
- Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
- Protocol parameters hash (current+pending): b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 301ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd data/genesis_snapshot_orig.bin
```

**Comment by HyperMindz** [comment]
image

**Comment by JM0unir** [comment]
✔️

```
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 484ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Comment by AdrianMarks** [comment]
Verified

calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 1.027s
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

**Comment by centercirclesolutions** [comment]
loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 782ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

**Comment by stowoxla** [comment]
nu da  :)

loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 828ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin

**Comment by adastraproterra** [comment]
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 01:00:00 +0100 CET
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 1.106s
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  genesis_snapshot_orig.bin

**Comment by TeeVeeEss** [comment]
```sh
sudo ./create_shimmer_genesis.sh
./create_shimmer_genesis.sh: line 3: [: missing `]'
loading protocol parameters ...
loading genesis addresses from file ...
loading genesis addresses from command line ...
Snapshot creation successful!
calculating ledger state hash ...
    >
        - Healthy:        YES
        - Tainted:        NO
        - Snapshot time:  1970-01-01 00:00:00 +0000 UTC
        - Network ID:     14364762045254553490
        - Treasury:       milestone ID 0x0000000000000000000000000000000000000000000000000000000000000000, tokens 0
        - Ledger index:   0
        - Snapshot index: 0
        - Pruning index:  0
        - UTXOs count:    100665
        - SEPs count:     1
        - Ledger token supply: 1813620509061365
        - Ledger state hash (w/o  solid entry points): 7d0f936370bdebd4442a5e29c63e42837d64a7cc67f502a8a03b31dd0d886242
        - Ledger state hash (with solid entry points): 249e5fa6fe4b855eb20ae0631bb859a318457e6e16189e74057235792cb077ca
        - Protocol parameters hash (current+pending):  b710fc3f08d6916fdbbc4cf9163f8ad311544b5f05598e1918656832c9f0a832

successfully calculated ledger state hash, took 868ms
calculating SHA256 hashes...
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot.bin
363eeb7940f2b07a62da25d6eefd086396f540e93e8ccc4fa0029036142e42fd  data/genesis_snapshot_orig.bin
```

**Review by TeeVeeEss — APPROVED** [review]

**Pull request merged**
